FROM postgres:16-alpine@sha256:57c72fd2a128e416c7fcc499958864df5301e940bca0a56f58fddf30ffc07777

ARG WALG_VERSION=3.0.0

RUN apk add --no-cache ca-certificates curl \
  && curl -fsSL \
    "https://github.com/wal-g/wal-g/releases/download/v${WALG_VERSION}/wal-g-linux-amd64" \
    -o /usr/local/bin/wal-g \
  && chmod +x /usr/local/bin/wal-g \
  && wal-g --version
